const INITIALIZE = 'INITIALIZE';
const NO_INITIALIZE = 'NO_INITIALIZE';
const CREATE_NEW_LIST = 'CREATE_NEW_LIST';
const UPDATE_ITEM = 'UPDATE_ITEM';
const UPDATE_LIST_ITEM_AT_INDEX = 'UPDATE_LIST_ITEM_AT_INDEX';
const TOGGLE_DONE = "TOGGLE_DONE";
const UPDATE_ITEM_NAME = 'UPDATE_ITEM_NAME';

export {
    INITIALIZE,
    NO_INITIALIZE,
    CREATE_NEW_LIST,
    UPDATE_ITEM,
    UPDATE_LIST_ITEM_AT_INDEX,
    TOGGLE_DONE,
    UPDATE_ITEM_NAME,
};